// This inventory describes implemented ownership, not a promise of feature support.
export const atomicLevels = [
  { id: 'foundations', title: 'Foundations', description: 'Shared visual values and assets; no application behavior.' },
  { id: 'atoms', title: 'Atoms', description: 'One control or visual responsibility.' },
  { id: 'molecules', title: 'Molecules', description: 'Related controls with one shared interaction contract.' },
  { id: 'organisms', title: 'Organisms', description: 'Complete task sections composed from smaller controls.' },
  { id: 'templates', title: 'Templates', description: 'Page structure and slots; separate from content-specific artwork.' },
  { id: 'examples', title: 'Pages and examples', description: 'Realistic compositions and experiments; not reusable production APIs.' },
]

export const libraryCatalog = [
  { name: 'SettingsPanel', level: 'organisms', status: 'Shared', source: 'src/components/design-system/organisms/SettingsPanel.jsx',
    purpose: 'Compose settings sections from divided description/control rows and a save footer.',
    properties: 'title, description, titleId, as, children, footer. SettingsRow: label, description, compact. SettingsFooter: message, error, children.',
    states: 'Responsive rows, status and error footer, consumer-supplied empty and deferred controls.',
    usage: 'Settings UI block examples; persistence is supplied by the consuming application.',
    constraints: 'Persistence belongs to the consumer. Rows stack below 600px container width; compact switch rows retain side-by-side layout.' },
  { name: 'FormField', level: 'molecules', status: 'Shared', source: 'src/components/design-system/molecules/FormField.jsx',
    purpose: 'Keep labels and validation adjacent to native fields or shared selection controls.',
    properties: 'label, hint, error, id, native input props; optional children({id, describedBy}) control slot.',
    states: 'Default, hover, focus, disabled, required, help and error.',
    usage: 'Settings names, email, API keys and labelled SelectMenu controls.',
    constraints: 'Caller owns value and validation. Associate custom controls with the supplied ID. Never prefill stored credentials.' },
  { name: 'Switch', level: 'atoms', status: 'Shared', source: 'src/components/design-system/atoms/Switch.jsx',
    purpose: 'Toggle a single boolean preference with canonical UI-control styling.',
    properties: 'label, checked, onChange, disabled, native button props.',
    states: 'On, off, hover, keyboard focus and disabled.',
    usage: 'Settings UI block and deferred notification preferences.',
    constraints: 'Use a visible label and native disabled semantics. Caller owns persistence; Enter and Space toggle.' },
  {
    name: 'SelectionTile', level: 'molecules', status: 'Shared', source: 'src/components/design-system/components/content/SelectionTile.tsx',
    purpose: 'Select or deselect one visual item through its entire surface.',
    properties: 'label, selected, onChange, disabled, children, caption, className.',
    states: 'Unselected, selected, hover, focus-visible and disabled. Native button with aria-pressed; Enter and Space toggle.',
    usage: 'Catalog visual-choice previews. The caller owns selection identities and persistence.',
    constraints: 'Children and captions must not contain interactive controls. Indicator reveals on hover, focus and touch, and remains visible when selected. Container layout belongs to the consumer.',
  },
  {
    name: 'InlineText', level: 'molecules', status: 'Shared', source: 'src/components/design-system/components/content/InlineText.tsx',
    purpose: 'Edit a saved text value in place while retaining drafts on failure.',
    properties: 'label, value, sourceKey, onSave(value, capturedSourceKey), onDirty, readOnly, maxLength (500), required, multiline.',
    states: 'Display, editing, saving, validation/error, changed-source notice, read-only. Enter saves; Shift+Enter adds a line; Escape cancels when idle.',
    usage: 'Catalog text-editing examples; the consumer owns parsing, validation and persistence.',
    constraints: 'Trims saved text. Return {ok:false,message} or throw to retain a failed draft. Captures sourceKey on edit entry; caller handles stale saves. Editable display target is at least 44px high.',
  },
  {
    name: 'FactGrid', level: 'molecules', status: 'Shared', source: 'src/components/design-system/components/content/FactGrid.tsx',
    purpose: 'Present ordered labelled facts with optional cell emphasis.',
    properties: 'items: [{id, label, value, emphasis?}]; label defaults to Details.',
    states: 'Default and accent-emphasized cells; content can be text or a shared editor.',
    usage: 'Catalog detail examples use a semantic definition list.',
    constraints: 'Unique item IDs and readable labels required. Two equal columns above 480px container width; one column at or below it, in source order. No domain validation or actions.',
  },
  {
    name: 'AsyncStatus', level: 'molecules', status: 'Shared', source: 'src/components/design-system/molecules/AsyncStatus.jsx',
    purpose: 'Describe ongoing indeterminate work with a status region and decorative loading icon.',
    properties: 'children: meaningful stage text supplied by the caller.',
    states: 'Mounted while work is pending; no internal request, completion or error state.',
    usage: 'Use for pending save, analysis or refinement operations supplied by a consumer.',
    constraints: 'Use actual stage wording; never simulated percentages. Caller owns timing, busy controls, requests and recovery.',
  },
  {
    name: 'UpdatedText', level: 'atoms', status: 'Shared', source: 'src/components/design-system/atoms/UpdatedText.jsx',
    purpose: 'Briefly acknowledge a saved text change within the same entity.',
    properties: 'value, identity; also exports useTextUpdate(value, identity) for an existing element.',
    states: 'Initial and identity-change values remain static; same-identity changes set a 200ms updated flag. Reduced motion removes the CSS animation.',
    usage: 'Use in an application shell to acknowledge saved titles.',
    constraints: 'Pass a stable entity identity. Visual acknowledgement only; does not persist text, manage editing or announce updates through a live region.',
  },
  {
    name: 'TextAction', level: 'atoms', status: 'Shared', source: 'src/components/design-system/components/actions/TextAction.tsx',
    purpose: 'A low-emphasis text action beneath related content.',
    properties: 'AppButton props and children; quiet, compact, underlined label.',
    states: 'Default, hover, focus, disabled, busy; native keyboard activation.',
    usage: 'Catalog upload and copy actions. The caller owns file handling and clipboard feedback.',
    constraints: 'Keeps a 44px touch target despite its small label. Use as="a" with href for navigation.',
  },
  {
    name: 'MediaWorkflowCard', level: 'organisms', status: 'Shared', source: 'src/components/design-system/organisms/MediaWorkflowCard.jsx',
    purpose: 'Present a labelled result with three ordered content areas.',
    properties: 'title, context, status, selected; columns: [{id, label, content, actions}].',
    states: 'Default and selected; source, loading, error and ready content is supplied by the caller.',
    usage: 'Catalog media-workflow examples; asset loading and generation stay in the consuming application.',
    constraints: 'Three columns at a card width of 720px; stacks in source order below it. Unique column IDs and readable labels required.',
  },
  {
    name: 'Application tokens', level: 'foundations', status: 'Shared', source: 'src/components/design-system/foundations/tokens.css', demo: 1,
    purpose: 'The light application palette, typography, spacing, shape, dimensions, and motion.',
    properties: 'Primitive palette → semantic --v2-* roles. Typography: H1–H5, Lead Large, Lead Medium, Body, Small text. Control height: 48px default / 44px compact. Icons: 16 / 20 / 24px.',
    states: 'Light theme; reduced motion through component CSS. Dark mode is not supported by the application.',
    usage: 'Consumed by the catalog and shared components. Use semantic roles in components; primitives only define the palette.',
    constraints: '--v2-muted is a palette sample, not body text. Use --v2-text-secondary. Legacy --accent/--ink remain compatibility tokens. Lucide icons are decorative unless given an accessible name.',
  },
  {
    name: 'AppButton', level: 'atoms', status: 'Shared', source: 'src/components/design-system/components/actions/AppButton.tsx', demo: 2, previewHref: '#components-buttons',
    purpose: 'Trigger an application action, including a pending operation.',
    properties: 'variant: primary | secondary (default) | danger | quiet; size: default | compact; iconOnly, busy, disabled: booleans; native button props and ref.',
    states: 'Default, hover, focus-visible, pressed, disabled, busy. Native states are not separate variants.',
    usage: 'Used by catalog specimens and PromptComposer. Place decorative icon children before or after the label.',
    constraints: 'Icon-only buttons require aria-label. Busy blocks repeated activation; the caller supplies a meaningful label. type defaults to button. Legacy variant="icon" maps to secondary + iconOnly.',
  },
  {
    name: 'TokenChip', level: 'atoms', status: 'Shared', source: 'src/components/design-system/atoms/TokenChip.jsx', demo: 1,
    purpose: 'Display a CSS token as a chip and copy its name to the clipboard.',
    properties: 'token: CSS custom-property name, such as --v2-accent. Composes AppButton.',
    states: 'Idle, hover, focus, copying, copied confirmation, failure with retry. Enter/Space activate.',
    usage: 'Typography and color values in the catalog. Documentation helper, not a package export.',
    constraints: 'Copies the exact token name, without var() or the resolved value. Requires browser clipboard access; confirms only after a successful write. Minimum 44px target.',
  },
  {
    name: 'TokenCopyTarget', level: 'atoms', status: 'Shared', source: 'src/components/design-system/atoms/TokenCopyTarget.jsx', demo: 1,
    purpose: 'Make a rendered value copyable while keeping the token name out of the specimen layout.',
    properties: 'copyValue: exact clipboard value; label: accessible copy description; children: rendered visual; className?.',
    states: 'Idle, hover, focus-visible, copying, copied confirmation, failure with retry. Enter/Space activate.',
    usage: 'Foundations uses this for color swatches, typography samples, and spacing markers.',
    constraints: 'The visual target remains a keyboard-operable 44px button. Copy feedback is exposed in a status region; the caller owns the displayed value and semantic token mapping.',
  },
  {
    name: 'Native inputs and selection controls', level: 'atoms', status: 'Examples only', source: 'src/components/design-system/examples/ControlSpecimens.jsx', demo: 2, previewHref: '#components-fields',
    purpose: 'Text input, textarea, native select, checkbox, radio, switch, file input, and disabled controls.',
    properties: 'Native value/defaultValue, checked, required, disabled, readOnly, min/max. These specimens do not export reusable control components.',
    states: 'Objective validation and disabled examples exist; full state coverage varies by control.',
    usage: 'Use FormField and shared controls when promoting an example to a product surface.',
    constraints: 'Labels must remain associated with controls; help/error IDs must be in aria-describedby. The file specimen advertises 25 MB but does not enforce it. Do not copy it as an uploader.',
  },
  {
    name: 'StatusLabel and progress', level: 'atoms', status: 'Examples only', source: 'src/components/design-system/examples/DataSpecimens.jsx', demo: 4,
    purpose: 'Communicate state with text plus a symbol; communicate known or unknown progress.',
    properties: 'Local StatusLabel: tone neutral | success | warning | danger, icon, children. Progress uses native ARIA values.',
    states: 'Draft, ready, review due, blocked; determinate and indeterminate examples.',
    usage: 'Promote a shared StatusBadge when a product needs a durable status contract.',
    constraints: 'A status badge is not an action or live region by default. Do not invent progress percentages for unknown generation work.',
  },
  {
    name: 'PillTabs + PillTabPanel', level: 'molecules', status: 'Shared', source: 'src/components/design-system/molecules/PillTabs.jsx', demo: 3, previewHref: '#components-tabs-and-view-controls',
    purpose: 'Choose one content panel with keyboard navigation and stable relationships.',
    properties: 'tabs: unique string labels; value; onChange(label); ariaLabel; idPrefix. Panel: tab, value, same idPrefix, children, className.',
    states: 'Selected/unselected, hover, focus; ArrowLeft/Right wrap; Home/End; automatic activation.',
    usage: 'Navigation specimens and product tab groups. Provide one panel per tab and a unique idPrefix per tab group.',
    constraints: 'For local content with immediate updates. No disabled/vertical/dynamic-tab support yet. Do not use tabs for routes or table density; use links or a segmented control.',
  },
  {
    name: 'SelectMenu', level: 'molecules', status: 'Shared', source: 'src/components/design-system/molecules/SelectMenu.jsx', demo: 2, previewHref: '#components-dropdowns',
    purpose: 'Choose one value from a small list with consistent focus and dismissal.',
    properties: 'label, value, options: unique strings, onChange(value), triggerLabel?, triggerId?, disabled?.',
    states: 'Open/closed, selected, focus, disabled; arrows wrap, Home/End, Enter/Space, Escape, outside click and blur.',
    usage: 'Used in prompt model/effort and language specimens, and Settings provider/model fields.',
    constraints: 'Controlled small-list selection; the consumer owns form persistence. No hidden form value, typeahead, multiple selection or async search. Keep options stable while open.',
  },
  {
    name: 'WorkflowSteps', level: 'molecules', status: 'Shared', source: 'src/components/design-system/molecules/WorkflowSteps.jsx', demo: 3, previewHref: '#components-workflow-steps',
    purpose: 'Expose an ordered workflow, its current step, and completion.',
    properties: 'items: label, context, complete, current, href?, disabled?; ariaLabel; onNavigate(index)?.',
    states: 'Complete/current/upcoming; optional disabled navigation; aria-current="step".',
    usage: 'Workflow examples map product state to steps. The component does not decide whether work is complete.',
    constraints: 'Classified as molecule because it owns only the ordered step interaction. The timeline with workflow rules is a feature organism. Disabled links prevent activation but remain discoverable.',
  },
  {
    name: 'Search, pickers and value controls', level: 'molecules', status: 'Examples only', source: 'src/components/design-system/examples/AdvancedControlSpecimens.jsx', demo: 2, previewHref: '#components-fields',
    purpose: 'Search, password visibility, currency, date range, combobox, single/multi-select, stepper, rating, and sliders.',
    properties: 'Local state and fixed example values; no reusable props contract. Native input constraints where shown.',
    states: 'Market filtering, no results, selected channels, bounded values, determinate/indeterminate progress.',
    usage: 'Use as isolated interaction examples until a shared contract is established.',
    constraints: 'Multi-select and searchable-combobox focus/dismissal still require extraction. Help text is not consistently associated. Do not treat every displayed control as production-ready.',
  },
  {
    name: 'Overlays and feedback', level: 'molecules', status: 'Examples only', source: 'src/components/design-system/examples/MotionSpecimens.jsx', demo: 7, previewHref: '#components-menu-and-supporting-information',
    purpose: 'Menu, tooltip, toast, inline confirmation and modal confirmation demonstrations.',
    properties: 'Internal open/closed state. Modal uses native dialog; local refs restore focus.',
    states: 'Open/closed; initial cancel focus, trapped modal focus, Escape and trigger restoration.',
    usage: 'Extract a shared menu or confirmation contract before using these patterns in a product.',
    constraints: 'Specimen modal is not a reusable Dialog API. Menu uses a group of buttons, not menu roles. Toast is local-only; there is no global notification queue.',
  },
  {
    name: 'PromptComposer', level: 'organisms', status: 'Shared', source: 'src/components/design-system/organisms/PromptComposer.jsx', demo: 11, previewHref: '#ds-preview-promptcomposer',
    purpose: 'Write a structured prompt, attach documents, and submit one request.',
    properties: 'value, onChange, files [{id,name}], onAttach(FileList), onRemove(id), onSubmit, canSubmit, busy, disabled, readOnly, hint, placeholder, submitLabel.',
    states: 'Empty/ready, attachment list, drag-over, busy/disabled, readable read-only. Ctrl/⌘+Enter submits; plain Enter adds a line.',
    usage: 'Catalog prompt examples. AppButton handles submission; the caller owns validation, extraction, errors, and requests.',
    constraints: 'Accepts TXT/MD/PDF/DOCX. The caller must enforce its own file-size and content limits. No model selector or slash commands. Never starts generation merely by mounting.',
  },
  {
    name: 'Catalog specimens', level: 'examples', status: 'Examples only', source: 'src/components/design-system/examples/', demo: 9,
    purpose: 'ControlSpecimens, NavigationSpecimens, FeedbackSpecimens, DataSpecimens, ContentObjectSpecimens, MotionSpecimens and ResponsiveSpecimen.',
    properties: 'No production data contract. SpecimenCard(title, description, children, className) and SpecimenSection(index, title, description, children) are documentation helpers.',
    states: 'Local demonstrations; responsive preview toggle, example data and interactive state showcases.',
    usage: 'DesignSystemScreen is the catalog composition; ApplicationDesignSystemPage is its route wrapper.',
    constraints: 'Sample names and metrics are illustrative. Render this catalog once per page because legacy specimens use fixed IDs. Examples do not establish production workflow support.',
  },
  {
    name: 'PromptInputBlock, SchedulingBlock, SettingsBlock', level: 'examples', status: 'Exploratory', source: 'src/components/design-system/examples/UIBlocks.jsx', demo: 10,
    purpose: 'Explore a command composer, review booking, and preferences in isolated local state.',
    properties: 'No external props; SelectMenu supplies the shared single-select interaction. Fixed availability and simulated completion.',
    states: 'Slash-command selection, simulated busy/cancel, time selection, dirty/save/cancel preferences.',
    usage: 'Optional examples only. Use PromptComposer when a structured prompt workflow is needed.',
    constraints: 'No real booking, AI model switching, persisted preferences, or application dark mode. The preview’s 25 MB contract and Enter-to-send do not apply to production.',
  },
]
